/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gabriel
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        mnu_princ = new javax.swing.JMenuBar();
        menuid_cid = new javax.swing.JMenu();
        menuidid_SP = new javax.swing.JMenuItem();
        menuidid_GRM = new javax.swing.JMenuItem();
        menuidid_STL = new javax.swing.JMenuItem();
        menuidid_LA = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuid_sair = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 240, 240));

        jDesktopPane1.setBackground(new java.awt.Color(0, 244, 200));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );

        menuid_cid.setText("Cidades");

        menuidid_SP.setText("São Paulo");
        menuidid_SP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuidid_SPActionPerformed(evt);
            }
        });
        menuid_cid.add(menuidid_SP);

        menuidid_GRM.setText("Gramado");
        menuidid_GRM.setToolTipText("");
        menuidid_GRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuidid_GRMActionPerformed(evt);
            }
        });
        menuid_cid.add(menuidid_GRM);

        menuidid_STL.setText("Seattle");
        menuidid_STL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuidid_STLActionPerformed(evt);
            }
        });
        menuid_cid.add(menuidid_STL);

        menuidid_LA.setText("Los Angeles");
        menuidid_LA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuidid_LAActionPerformed(evt);
            }
        });
        menuid_cid.add(menuidid_LA);

        mnu_princ.add(menuid_cid);

        jMenu1.setText("Desenvolvedor");

        jMenuItem2.setText("Desenvolvedor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        mnu_princ.add(jMenu1);

        menuid_sair.setText("Sair");

        jMenuItem7.setText("Sair");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menuid_sair.add(jMenuItem7);

        mnu_princ.add(menuid_sair);

        setJMenuBar(mnu_princ);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void menuidid_SPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuidid_SPActionPerformed
        frmSP frm = new frmSP();
        frm.setVisible(true);
        jDesktopPane1.add(frm);
    }//GEN-LAST:event_menuidid_SPActionPerformed

    private void menuidid_GRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuidid_GRMActionPerformed
        frmGramado frm = new frmGramado();
        frm.setVisible(true);
        jDesktopPane1.add(frm);
    }//GEN-LAST:event_menuidid_GRMActionPerformed

    private void menuidid_STLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuidid_STLActionPerformed
        Seattle frm = new Seattle();
        frm.setVisible(true);
        jDesktopPane1.add(frm);
    }//GEN-LAST:event_menuidid_STLActionPerformed

    private void menuidid_LAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuidid_LAActionPerformed
        frmLA frm = new frmLA();
        frm.setVisible(true);
        jDesktopPane1.add(frm);
    }//GEN-LAST:event_menuidid_LAActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        frmDes frm = new frmDes();
        frm.setVisible(true);
        jDesktopPane1.add(frm);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenu menuid_cid;
    private javax.swing.JMenu menuid_sair;
    private javax.swing.JMenuItem menuidid_GRM;
    private javax.swing.JMenuItem menuidid_LA;
    private javax.swing.JMenuItem menuidid_SP;
    private javax.swing.JMenuItem menuidid_STL;
    private javax.swing.JMenuBar mnu_princ;
    // End of variables declaration//GEN-END:variables
}
